VSCODE_VERSION=		1.128.0
SOURCE_COMMIT_HASH=	fc3def6774c76082adf699d366f31a557ce5573f
# See ${WRKSRC}/build/rspack/node_modules/@rspack/binding/package.json for rspack version
RSPACK_VERSION=		2.1.2
# See ${WRKSRC}/node_modules/@github/copilot/package.json for copilot cli version
COPILOT_CLI_VERSION=	1.0.67
