VSCODE_VERSION=		1.136.1
SOURCE_COMMIT_HASH=	a44adf7f53e00964ab890f9f8758a334f1fc15bc
# See ${WRKSRC}/build/rspack/node_modules/@rspack/binding/package.json for rspack version
RSPACK_VERSION=		2.1.2
# See ${WRKSRC}/extensions/copilot/node_modules/@github/copilot/package.json for copilot cli version
COPILOT_CLI_VERSION=	1.0.73
# See ${WRKSRC}/node_modules/@vscode/os-proxy-resolver/package.json for os-proxy-resolver version
OS_PROXY_RESOLVER_VERSION=	0.4.0
